# Flags
WVGA_FLAG=0
HD_FLAG=1
EXTRA_CFLAGS += -DMPU_SENSORS_MPU6050B1=1

# VU
obj-$(CONFIG_MACH_VU10)				+= board-x3.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-kbc.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-panel.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-power.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-sdhci.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-sensors.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-memory.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-usb.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-bt.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-audio.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-misc.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-input.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-i2c-dev.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-gps.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-baseband.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-pinmux.o
obj-$(CONFIG_MACH_VU10)				+= board-x3-nv.o

obj-$(CONFIG_REBOOT_MONITOR)		+= board-x3-reboot.o
